### ISSUE TITLE
Symfony 6 Support

### ISSUE THREAD

**Issue by brandon-welsch** [Scalingo/sample-php-symfony#12]
A freshly created Symfony 6 app is available here with some settings already done: https://github.com/brandon-welsch/scalingo-sample-php-symfony6

Some of the work has already been done, now we need to finish this work so that the Scalingo repository is updated to version 6 and the documentation is up to date. Feel free to clone my repository to finish the work

Remaining tasks:

- [ ] Test what's in the Scalingo documentation for Symfony 4/5 for this new version (log files, database migration, reverse proxy settings are applied, but check if it work properly)
- [ ] Update our documentation about reverse proxy for Symfony 6, the code is located elsewhere and it's not the same as the other versions
- [ ] Also add in the Symfony page a link to https://doc.scalingo.com/languages/php/php-nodejs to show how to deploy Symfony with nodejs (webpack ...). 
- [ ] Maybe need more work to explain how it work with webpack encore: https://symfony.com/doc/current/frontend.html#webpack-encore (postdeploy command ? Or auto-scripts/post-install-cmd from composer.json)
- [ ] Make the final PR to upgrade the Scalingo sample to Symfony 6 with a great README.md and scalingo.json (APP_ENV, APP_DEBUG envs) file.
- [ ] Add a `v6` tag when the previous PR is done and merged in master.

**Comment by guillaume-sc** [comment]
This ticket had no traction since it was created end of 2021. Please document and re-open if necessary.
